### PR TITLE
Feature/reindex people

### PR DESCRIPTION
**Pull request by ericgriffis**
@hab278 How does this look?

### CODE REVIEW

**Comment by hab278** [comment]
@ericgriffis Let's do a code review!

**Comment by barnabyalter** [comment]
@hab278 with more time i'd agree. but i think if @ericgriffis can get this passing travis then we should merge. also keep the coverage at 100% if you can.

**Comment by ericgriffis** [comment]
@barnabyalter @hab278  I don't know why it says coverage decreased when I wrote unit tests for every method? Also travis build is only failing because its missing the environment variable for the api key -- should I connect configula to the project so it passes? or how is that handled?

**Comment by hab278** [comment]
@ericgriffis Probably decreased coverage because its not passing on travis so its missing a step. Configula wont solve the failures, you'd have to fake it

**Comment by barnabyalter** [comment]
@ericgriffis definitely a strange failure. i can't reproduce locally and the failures its showing are older tests that dont require configula. i reran it just to see if it was a fluke.

**Comment by hab278** [comment]
@barnabyalter @ericgriffis looks like its passing now

**Pull request merged**
